### PR TITLE
Change to Modular Extension

### PR DESCRIPTION
**Pull request by garethrees**
I was having some trouble using FistFace with other Sinatra extensions, so as a first step I made it in to a 'modular' extension style. Its also inline with the Sinatra "Rules for Extensions" http://www.sinatrarb.com/extensions.html#rules_for_extensions

### CODE REVIEW

**Comment by mike-burns** [comment]
Hi Gareth,

I see you added a Rakefile, but I couldn't get rake to run:

```
~/lib/fistface% bundle exec rake
/var/lib/gems/1.8/gems/bundler-1.0.12/lib/bundler/shared_helpers.rb:107:in `gem': rake is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
    from /var/lib/gems/1.8/bin/rake:18
```

When I tried running the specs I got this error:

```
~/lib/fistface% bundle exec rspec spec 
/var/lib/gems/1.8/gems/rspec-core-2.4.0/lib/rspec/core/backward_compatibility.rb:20:in `const_missing': uninitialized constant FistFace (NameError)
    from /home/mike/lib/fistface/spec/fistface_spec.rb:3
    from /var/lib/gems/1.8/gems/rspec-core-2.4.0/lib/rspec/core/configuration.rb:387:in `load'
    from /var/lib/gems/1.8/gems/rspec-core-2.4.0/lib/rspec/core/configuration.rb:387:in `load_spec_files'
    from /var/lib/gems/1.8/gems/rspec-core-2.4.0/lib/rspec/core/configuration.rb:387:in `map'
    from /var/lib/gems/1.8/gems/rspec-core-2.4.0/lib/rspec/core/configuration.rb:387:in `load_spec_files'
    from /var/lib/gems/1.8/gems/rspec-core-2.4.0/lib/rspec/core/command_line.rb:18:in `run'
    from /var/lib/gems/1.8/gems/rspec-core-2.4.0/lib/rspec/core/runner.rb:55:in `run_in_process'
    from /var/lib/gems/1.8/gems/rspec-core-2.4.0/lib/rspec/core/runner.rb:46:in `run'
    from /var/lib/gems/1.8/gems/rspec-core-2.4.0/lib/rspec/core/runner.rb:10:in `autorun'
    from /var/lib/gems/1.8/bin/rspec:19
```

**Comment by garethrees** [comment]
I've made the tests work now (wooo!).

I'm not actually sure whether I need the Rakefile. I added it in as it lets you do `rake install` to install the gem locally. Should I just get rid of it?

**Comment by garethrees** [comment]
I've made the tests work now (wooo!).

I'm not actually sure whether I need the Rakefile. I added it in as it lets you do `rake install` to install the gem locally. Should I just get rid of it?

**Comment by mike-burns** [comment]
The Rakefile still doesn't work but the specs pass. Removing the Rakefile for now.

**Pull request merged**
